### ISSUE TITLE
ReferenceError: Unknown plugin "runtime"

### ISSUE THREAD

**Issue by omerts** [babel-plugins/babel-plugin-runtime#3] opened 2015-08-12 12:55 UTC
Trying to use this plugin I get the above error. I know I could use the optional: ['runtime'] config, but I want to use this plugin, and change it to suit my needs.

**Comment by sebmck** [comment] 2015-08-12 18:02
Duplicate of #1. `optional: ['runtime']` is literally this plugin so there's isn't really any difference. Better support for the abstracted out plugins is being tracked in babel/babel#1995. Thanks! :blush:

**Closed by sebmck** 2015-08-12 18:02 UTC

**Comment by omerts** [comment] 2015-08-13 07:26
@sebmck Thanks for the answer. As I said, I know of the optional config, but I am trying to use this plugin as a base for a plugin I am trying to write.

**Comment by omerts** [comment] 2015-08-13 07:48
I think I am getting this error because I am trying to run the transformation in browser.

**Comment by omerts** [comment] 2015-08-13 08:04
Ok ended up using:
```javascript
 { plugins: [require('../babel-plugin-playground')]}
```
and just in case anyone running into the same problem, and also wants to control the position (before | after):
```javascript
{ plugins: [{transformer: require('../babel-plugin-playground'), position: 'after'}]}
```
@sebmck Great thinking about all the use cases in the plugin manager code

**Comment by omerts** [comment] 2015-08-13 08:18
Added examples to docs:
https://github.com/babel/babel.github.io/pull/410
